---
# tasks file for user
- name: create group panda
  ansible.builtin.group:
    name: panda
    state: present
    gid: 1234
- name: create user panda
  ansible.builtin.user:
    name: panda
    groups:
      - panda
      - sudo
    uid: 1234
    shell: /bin/bash
- name: set authorized_keys for panda user from vagrant user
  authorized_key:
    user: panda
    state: present
    key: "{{ lookup('file', '/home/vagrant/.ssh/authorized_keys') }}"