---
- name: init
  hosts: all
  become: true
  vars:
    docker_users:
      - panda
      - vagrant
    docker_daemon_options:
      insecure_registries:
        ["192.168.56.200"]
  roles:
    - user
    - packages
    - geerlingguy.docker
    - christianganda.awscli
    - christianganda.awscli_configure
    - diodonfrost.terraform