---
- name: init
  hosts: all
  become: true
  vars:
    docker_users:
      - panda
      - vagrant
  roles:
    - user
    - packages
    - geerlingguy.docker
    - christianganda.awscli
    - christianganda.awscli_configure
    - diodonfrost.terraform